# Generated by Django 4.2.16 on 2026-08-31 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('opportunity_type', models.CharField(choices=[('STAGE', 'Stage'), ('EMPLOI', 'Emploi'), ('FREELANCE', 'Freelance'), ('HACKATHON', 'Hackathon'), ('FORMATION', 'Formation'), ('PROJET', 'Projet')], max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('deadline', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
