# Generated by Django 4.2.7 on 2026-08-31 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('study_level', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Compétences séparées par des virgules')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('bio', models.TextField(blank=True)),
                ('is_active_member', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='members/qrcodes/')),
                ('membership_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
